### ISSUE TITLE
Detail page

### ISSUE THREAD

**Issue by hjconehour** [hjconehour/onehouraday#2]
Main Goal
- Let users understand what a Social project is about, what's needed and offer their help

Acceptance Criteria
- A brief of the project should be displayed
- What work needs to be done should be clear for the user
- Users should be able to apply for a "Task"  to be done
- Users should be able to contact the social project team

Wireframe
![view ngo 2](https://user-images.githubusercontent.com/3884690/33238471-a4a06af6-d28e-11e7-842a-939436d6bb5d.png)

**Comment by andy-shi88** [comment]
Hello @hjconehour could you explain more about the stack? wether you split up backend and the frontend development and what technology are you using for this project? would love to help.

**Comment by hjconehour** [comment]
Hi @andy-shi88 .  The team is building everything from scratch.  If you want more info you can join to our slack channel and speak directly with the devs.

**Comment by andy-shi88** [comment]
can you invite me to the channel? @hjconehour here is my email shi88.andy@gmail.com
