### ISSUE TITLE
Add contact instructions for people who want to be on the slack channel

### ISSUE THREAD

**Issue by ginna-baker** [hjconehour/onehouraday#34]
Contributors can't view the slack channel unless they are invited.  In the readme, we need a contact email or other contact method so that would-be contributors can ask to be invited to the slack.

**Comment by hjconehour** [comment]
Great point Ginna. I will take this one.

**Comment by hjconehour** [comment]
https://github.com/hjconehour/onehouraday/wiki/How-people-get-communicated%3F

**Comment by ginna-baker** [comment]
Looking good
