### ISSUE TITLE
Add Social Project

### ISSUE THREAD

**Issue by hjconehour** [hjconehour/onehouraday#4]
# Goal
People or organisations that have social projects should be able to publish their projects in order to seek for "Helpers"  (People who can dedicate a specific time to solve a specific need/problem. 

# Acceptance Criteria

* Should be able to publish a new project
* Should be able edit an existing project.
* Should be able to remove my uploaded project

# Wireframe
![publish_new 1](https://user-images.githubusercontent.com/3884690/33238500-67285700-d28f-11e7-9dd8-544c2b9bc015.png)

**Comment by danieldiaz14** [comment]
Hey there!

I got accepted on Code for Social good on this project! I would like to claim this issue!

**Comment by hjconehour** [comment]
Hi Daniel,

Thanks for joining!

I have gave you access to our slack channel. Please let me know if you
received it.

Thanks



2018-01-12 22:14 GMT+01:00 Daniel Diaz Medrano <notifications@github.com>:
